import { createApp } from "vue";
import "./style.css";
import App from "./App.vue";
import routes from "./routes";
import { createPinia } from "pinia";
import "element-plus/dist/index.css";
const app = createApp(App);
app.use(routes);
app.use(createPinia());
app.mount("#app");
